[package]
name = "cpf"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.32.2"
glutin-winit = "0.5.0"
anyhow = "1.0.97"
glow = "0.14.0"
imgui = "0.12.0"
imgui-glow-renderer = "=0.13.0"
imgui-winit-support = "0.13.0"
raw-window-handle = "0.6.2"
winit = "0.30.9"
