name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --lib --examples
    - name: Check
      run: cargo check --lib --examples
    - name: Check formatting
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy --lib --examples
    - name: Run tests
      run: cargo test --verbose --lib --examples
